import { NextRequest, NextResponse } from "next/server";
import { ConvexHttpClient } from "convex/browser";
import { api } from "../../../../convex/_generated/api";

// ---------------------------------------------------------------------------
// Google OAuth 2.0 callback handler
// Flow:
//   1. User clicks "Connect Google Calendar" → opens popup to /api/google-start
//   2. /api/google-start sets HttpOnly cookie with nonce+token, redirects to Google
//   3. Google redirects to this endpoint with ?code=...&state=<nonce>
//   4. We read the nonce from the cookie, verify it matches state (CSRF check),
//      extract the Clerk token from the cookie, exchange the code for tokens,
//      and save the refresh token to Convex via the authenticated session.
//   5. We return an HTML page that closes the popup + signals success to parent.
// ---------------------------------------------------------------------------

const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";

/** Parse a specific cookie value from a Cookie header string. */
function parseCookie(cookieHeader: string | null, name: string): string | null {
  if (!cookieHeader) return null;
  for (const part of cookieHeader.split(";")) {
    const [k, ...rest] = part.trim().split("=");
    if (k?.trim() === name) return rest.join("=");
  }
  return null;
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const code = searchParams.get("code");
  const state = searchParams.get("state"); // nonce generated by /api/google-start
  const error = searchParams.get("error");

  if (error || !code || !state) {
    return new NextResponse(closePopupHtml("error", "Google authorization was denied or failed."), {
      headers: { "Content-Type": "text/html" },
    });
  }

  // ── CSRF / session-binding check ─────────────────────────────────────────
  // The cookie was set by /api/google-start and is HttpOnly + SameSite=Lax.
  // Its nonce must match the `state` param to confirm this callback belongs
  // to the OAuth session we initiated (prevents CSRF and token-hijacking).
  const rawCookie = parseCookie(req.headers.get("cookie"), "_goauth_state");
  if (!rawCookie) {
    return new NextResponse(
      closePopupHtml("error", "OAuth session expired or missing. Please try again."),
      { headers: { "Content-Type": "text/html" } }
    );
  }

  let cookieNonce: string;
  let token: string;
  try {
    const payload = JSON.parse(Buffer.from(rawCookie, "base64").toString());
    cookieNonce = payload.nonce;
    token = payload.token;
  } catch {
    return new NextResponse(
      closePopupHtml("error", "Invalid OAuth session. Please try again."),
      { headers: { "Content-Type": "text/html" } }
    );
  }

  if (!cookieNonce || !token || state !== cookieNonce) {
    return new NextResponse(
      closePopupHtml("error", "OAuth state mismatch. Please try again."),
      { headers: { "Content-Type": "text/html" } }
    );
  }

  const clientId = process.env.GOOGLE_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
  const redirectUri = process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URI;

  if (!clientId || !clientSecret || !redirectUri) {
    return new NextResponse(closePopupHtml("error", "Google OAuth is not configured on this server."), {
      headers: { "Content-Type": "text/html" },
    });
  }

  // Clear the cookie immediately — one-time use
  const isProduction = process.env.NODE_ENV === "production";
  const securFlag = isProduction ? "; Secure" : "";
  const clearCookieHeader = `_goauth_state=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${securFlag}`;

  try {
    // Exchange authorization code for access + refresh tokens
    const tokenRes = await fetch(GOOGLE_TOKEN_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        code,
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uri: redirectUri,
        grant_type: "authorization_code",
      }),
    });

    if (!tokenRes.ok) {
      const err = await tokenRes.json().catch(() => ({}));
      console.error("Token exchange failed:", err);
      return new NextResponse(closePopupHtml("error", "Failed to exchange authorization code."), {
        headers: { "Content-Type": "text/html", "Set-Cookie": clearCookieHeader },
      });
    }

    const tokens = await tokenRes.json();
    const refreshToken: string = tokens.refresh_token;

    if (!refreshToken) {
      return new NextResponse(
        closePopupHtml("error", "No refresh token received. Please revoke app access in your Google account and try again."),
        { headers: { "Content-Type": "text/html", "Set-Cookie": clearCookieHeader } }
      );
    }

    // Get the user's Google email via userinfo endpoint
    const userInfoRes = await fetch("https://www.googleapis.com/oauth2/v2/userinfo", {
      headers: { Authorization: `Bearer ${tokens.access_token}` },
    });
    const userInfo = userInfoRes.ok ? await userInfoRes.json() : {};
    const googleEmail: string = userInfo.email ?? "";

    // Save tokens to Convex using the Clerk session token from the cookie
    const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
    if (!convexUrl) throw new Error("NEXT_PUBLIC_CONVEX_URL not set");

    const convex = new ConvexHttpClient(convexUrl);
    convex.setAuth(token);

    await convex.mutation(api.users.mutations.saveGoogleTokens, {
      googleRefreshToken: refreshToken,
      googleEmail,
    });

    return new NextResponse(closePopupHtml("success", ""), {
      headers: { "Content-Type": "text/html", "Set-Cookie": clearCookieHeader },
    });
  } catch (err) {
    console.error("Google OAuth callback error:", err);
    return new NextResponse(closePopupHtml("error", "An unexpected error occurred."), {
      headers: { "Content-Type": "text/html", "Set-Cookie": clearCookieHeader },
    });
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");
}

function closePopupHtml(status: "success" | "error", message: string): string {
  const safeMessage = escapeHtml(message);
  const isSuccess = status === "success";
  return `<!DOCTYPE html>
<html>
<head><title>Google Calendar Authorization</title></head>
<body style="font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#f9fafb">
  <div id="result" data-status="${isSuccess ? "success" : "error"}" style="text-align:center;padding:32px;background:#fff;border-radius:12px;box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:360px">
    ${isSuccess
      ? `<div style="color:#16a34a;font-size:48px">&#10003;</div>
         <h2 style="color:#111;margin:16px 0 8px">Google Calendar Connected</h2>
         <p style="color:#6b7280">You can now create appointments with Google Meet links. This window will close shortly.</p>`
      : `<div style="color:#dc2626;font-size:48px">&#10007;</div>
         <h2 style="color:#111;margin:16px 0 8px">Authorization Failed</h2>
         <p style="color:#6b7280">${safeMessage}</p>
         <button onclick="window.close()" style="margin-top:16px;padding:10px 24px;background:#1d4ed8;color:#fff;border:none;border-radius:6px;cursor:pointer">Close</button>`
    }
  </div>
  <script>
    var el = document.getElementById("result");
    if (el && el.dataset.status === "success") {
      if (window.opener) {
        window.opener.postMessage("google-connected", window.location.origin);
      }
      setTimeout(function() { window.close(); }, 2000);
    }
  </script>
</body>
</html>`;
}
